### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by sinwoobang** [stewartpark/git-play#4]
Hi, stewart.

Do you have any plans to apply PEP 8?
If so, I will try once.

Thanks.

**Comment by stewartpark** [comment]
Hi Bang,

Truth be told, this project started out as a toy project but I think it gained enough popularity to consider how we can improve the productivity side -- adopting a clean, well-designed coding convention that everyone agrees upon, such as PEP8, would be a good start in terms of future development and attracting more people to this project.

It would be much appreciated if you could work on it and send a PR.

Thanks for the great idea and participation.
